apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: staging
  labels:
    app: frontend-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - venudev.duckdns.org
      secretName: frontend-tls
  rules:
    - host: venudev.duckdns.org
      http:
        paths:
          - path: /staging
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
