apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - venudev.duckdns.org
      secretName: venudev-tls
  rules:
    - host: venudev.duckdns.org
      http:
        paths:
          - path: /staging
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
