apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: staging-kustomization
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/staging/
  prune: true
  sourceRef:
    kind: GitRepository
    name: staging-app
  targetNamespace: staging
